### ISSUE TITLE
Hello

### ISSUE THREAD

**Issue by staticdev** [cjolowicz/cjolowicz#1]
Hope you are fine, miss you on GH.

There are lots of changes since last release of [cookiecutter-hypermodern-python](https://github.com/cjolowicz/cookiecutter-hypermodern-python), good time to release a new version?

Have a nice weekend.

**Comment by cjolowicz** [comment]
Hey @staticdev :) Thanks for dropping a note here! Fully agree that it's time to release the project template. It's been a busy few months, but the release should come real soon now (TM).
